# Generated by Django 2.2.2 on 2020-01-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_diary_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='number',
            field=models.IntegerField(default=0, verbose_name='参加人数'),
        ),
        migrations.AddField(
            model_name='diary',
            name='restaurant',
            field=models.TextField(null=True, verbose_name='店名'),
        ),
        migrations.AddField(
            model_name='diary',
            name='schedule',
            field=models.DateTimeField(null=True, verbose_name='予定日'),
        ),
        migrations.AddField(
            model_name='diary',
            name='station',
            field=models.TextField(blank=True, null=True, verbose_name='最寄り駅'),
        ),
        migrations.AddField(
            model_name='diary',
            name='want',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='行きたい'),
        ),
        migrations.AddField(
            model_name='diary',
            name='wanttext',
            field=models.TextField(blank=True, default='', null=True, verbose_name='行きたい人達'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.TextField(verbose_name='タイトル'),
        ),
    ]
