# Generated by Django 2.2.2 on 2020-01-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200115_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='want',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='wanttext',
        ),
    ]
