# Generated by Django 2.2.2 on 2020-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='want',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='行きたい'),
        ),
        migrations.AddField(
            model_name='diary',
            name='wanttext',
            field=models.TextField(blank=True, default='', null=True, verbose_name='行きたい人達'),
        ),
    ]
