# Generated by Django 2.2.2 on 2020-01-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200115_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='want',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='wanttext',
        ),
    ]
