# Generated by Django 2.2.2 on 2020-01-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200115_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='wanttext',
            field=models.TextField(blank=True, default=',', null=True, verbose_name='行きたい人達'),
        ),
    ]
