# Generated by Django 2.2.2 on 2020-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20200118_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='want',
            field=models.IntegerField(default=0, null=True, verbose_name='行きたい'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='wanttext',
            field=models.TextField(default=',', null=True, verbose_name='行きたい人達'),
        ),
    ]
