# Generated by Django 2.2.2 on 2020-01-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='アイコン'),
        ),
    ]
